"""LangChain @tool functions for all agents.

Tools: web_search, read_url, knowledge_search, save_report.
Sub-agents (planner, researcher, critic) share the first three;
save_report is used only by the Supervisor and is HITL-gated.
"""

import os
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime
from pathlib import Path

import trafilatura
from ddgs import DDGS
from langchain_core.tools import tool

from config import Settings

settings = Settings()

_executor = ThreadPoolExecutor(max_workers=4)


def _ddgs_search(query: str, max_results: int) -> list[dict]:
    return DDGS().text(query, max_results=max_results)


@tool
def web_search(query: str) -> str:
    """Search the web using DuckDuckGo. Returns titles, URLs, and snippets."""
    try:
        future = _executor.submit(_ddgs_search, query, settings.max_search_results)
        results = future.result(timeout=30)
        if not results:
            return "No results found."
        formatted = []
        for i, r in enumerate(results, 1):
            formatted.append(
                f"{i}. Title: {r.get('title', 'N/A')}\n"
                f"   URL: {r.get('href', 'N/A')}\n"
                f"   Snippet: {r.get('body', 'N/A')}"
            )
        result = "\n\n".join(formatted)
        if len(result) > settings.max_search_content_length:
            result = result[: settings.max_search_content_length] + "\n\n[... truncated]"
        return result
    except Exception as e:
        return f"Search error: {e}"


@tool
def read_url(url: str) -> str:
    """Fetch and extract the main text content from a web page."""
    try:
        config = trafilatura.settings.use_config()
        config.set("DEFAULT", "DOWNLOAD_TIMEOUT", "10")
        downloaded = trafilatura.fetch_url(url, config=config)
        if downloaded is None:
            return f"Error: Could not fetch URL: {url}"
        text = trafilatura.extract(downloaded)
        if not text:
            return f"Error: Could not extract text from: {url}"
        if len(text) > settings.max_url_content_length:
            text = text[: settings.max_url_content_length] + "\n\n[... truncated]"
        return text
    except Exception as e:
        return f"Error reading URL: {e}"


@tool
def knowledge_search(query: str) -> str:
    """Search the local knowledge base (RAG) using hybrid retrieval + reranking.

    Use for questions about topics covered in ingested documents (RAG, LLMs,
    LangChain, NLP, embeddings, vector search). Returns relevant text chunks
    with source and page refs.
    """
    try:
        from retriever import retrieve

        results = retrieve(query)
        if not results:
            return "No relevant documents found in the knowledge base."
        formatted = []
        for i, doc in enumerate(results, 1):
            source = Path(doc.metadata.get("source", "unknown")).name
            page = doc.metadata.get("page", "?")
            formatted.append(f"{i}. [Source: {source}, Page: {page}]\n{doc.page_content}")
        result = "\n\n---\n\n".join(formatted)
        if len(result) > settings.max_search_content_length:
            result = result[: settings.max_search_content_length] + "\n\n[... truncated]"
        return result
    except Exception as e:
        return f"Knowledge search error: {e}"


@tool
def save_report(filename: str, content: str) -> str:
    """Save a Markdown research report to the output directory.

    This tool requires human approval before saving.
    """
    return _do_save(filename, content)


def _do_save(filename: str, content: str) -> str:
    """Actually write the report file to disk."""
    try:
        os.makedirs(settings.output_dir, exist_ok=True)
        if not filename.endswith(".md"):
            filename += ".md"
        timestamp = datetime.now().strftime("%Y-%m-%d_%H%M")
        full_name = f"{timestamp}_{filename}"
        filepath = os.path.join(settings.output_dir, full_name)
        meta = f"> Generated by Multi-Agent Research System on {datetime.now().strftime('%Y-%m-%d %H:%M')}\n\n"
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(meta + content)
        return f"Report saved successfully to: {filepath}"
    except Exception as e:
        return f"Error saving report: {e}"


# Convenience groupings for sub-agents
RESEARCH_TOOLS = [web_search, read_url, knowledge_search]
PLANNER_TOOLS = [web_search, knowledge_search]
CRITIC_TOOLS = [web_search, read_url, knowledge_search]
